### ISSUE TITLE
App crashes every second time when a song is added to created playlist

### ISSUE THREAD

**Issue by crysports** [Crypto-Android-Apps/ACG-Player#56]
I clicked on a song and created a new playlist and added that song to the playlist.
I tried to add another song to the same playlist and the application crashed.
Here is a video
https://youtu.be/Ocl3MKPYtog

**Comment by AugustToko** [comment]
exit App and wipe data, try again

**Comment by crysports** [comment]
It is still present.
Actually when you create a new playlist and add a song for the first time, the app works fine. But whenever you try to add more songs to that playlist, the app crashes everytime.

**Comment by AugustToko** [comment]
> It is still present.
> Actually when you create a new playlist and add a song for the first time, the app works fine. But whenever you try to add more songs to that playlist, the app crashes everytime.

The strange thing is that it works fine on my device. Can you give me a log?

**Comment by umair1209** [comment]
I have no knowledge about how to generate a log but I will try .

**Comment by crysports** [comment]
I have no knowledge about logs but I will try.

**Comment by AugustToko** [comment]
> I have no knowledge about logs but I will try.

Thanks, just use the adb tool

**Comment by AugustToko** [comment]
try new version on release page.
I added a log function to it, which can record crashes and then send them to the cloud. So I can locate the cause of the crash.

**Comment by crysports** [comment]
Alright.
I will let you know

**Comment by crysports** [comment]
I am unable to replicate the bug now. Looks like it is fixed now but the songs are not added to the created playlist.
I will attach a video soon.

**Comment by crysports** [comment]
https://youtu.be/HosDxoJH2vU

**Comment by AugustToko** [comment]
remove this playlist and exit App and wipe data
Very strange, he works very well on my device...

**Comment by crysports** [comment]
Working now

**Comment by AugustToko** [comment]
try new version

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
