### ISSUE TITLE
App crashing when screen recorder is on

### ISSUE THREAD

**Issue by cckole** [Crypto-Android-Apps/ACG-Player#59]
**Describe the bug**
I wanted to record a bug and I tapped the Du screen recorder after which I clicked on ACG- player. It's surprising that the app refused to open. It crashes each time I tried to reproduce using a screen recorder. If I launch the app without using the screen recorder, it launches without crashing.

**To Reproduce**
1. Get a screen recorder.(I tried it with DU Recorder and AZ screen recorder)
2. start the screen recorder
3. lauch the app

**Expected behavior**
I expected the app to launch even with screen recorder on.

**Screenshots**
![20190602_224306](https://user-images.githubusercontent.com/36272218/58767856-17ee0780-8589-11e9-8086-49895bd0a69d.gif)

**Smartphone (please complete the following information):**
 - Device: [tecno spark k7]
 - OS: [Android 7.0]
 - Version [2.6.5.9]

**Additional context**
This is a very strange behaviour.

**Comment by AugustToko** [comment]
I also find it very strange. Is there a log to let me locate this bug?

**Comment by cckole** [comment]
I couldn't get the log because it wasn't reproduceable anymore in the subsequent versions.

**Comment by AugustToko** [comment]
> I couldn't get the log because it wasn't reproduceable anymore in the subsequent versions.

Ok, it might be an accidental mistake.

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
