### ISSUE TITLE
Clicking on force use net album crashes the app.

### ISSUE THREAD

**Issue by crysports** [Crypto-Android-Apps/ACG-Player#61]
I opened one of the albums on the app and from the top right corner of the screen, I clicked on menu and then clicked on force use net album, the application crashed.

https://youtu.be/QR-ijaNfYN4

**Comment by AugustToko** [comment]
Ok, I will locate the bug based on the log.

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
