### ISSUE TITLE
Add “Online Music", “Google Assistant", “Sleep Timer" and “Sort" feature to ACG-Player.

### ISSUE THREAD

**Issue by Xeeshuu** [Crypto-Android-Apps/ACG-Player#69]
#### **Components:**
I propose to add some features in settings and few other features which will connect it to online music.
#### **Proposal:**
The features i proposed to add are mentioned below:
* **Online Music:** This feature is one of the best amongst all of other features which i propose to implement. This feature will help user to connect with online music system, which will help him in saving time as well as storage too.
* **Google Assistant:** This is a very handy feature in a music player as the users will just have to command via voice and the assistant will do the rest.
* **Sleep Timer:** As we all know that everyone is addictive to listen music for long long time, but most of them left it as it is. With the helo of this feature user can set some time to listen music and after that it will stop streaming automatically after the set time.
* **Sort:**  Now this feature might be a little trivial but this will be a great addition to the application. If you have plenty of songs in the playlist, you will need sort feature to select the genre according to your mood. 
#### Mockups/Examples:
* Implementation of “Online Music" in app:
![PicsArt_06-14-11.51.38.png](https://cdn.steemitimages.com/DQmawJcjCoYZUoTfRcz6kHKrWd5XvcLijV1Evuoz7hhg6eH/PicsArt_06-14-11.51.38.png)
* Implementation of “Google Assistant" feature to the app:
![PicsArt_06-14-11.52.40.png](https://cdn.steemitimages.com/DQmc5ori5TDxxPYcLc7XfpGgmzNCzjKBHUTgai5FC6CiTTH/PicsArt_06-14-11.52.40.png)
* Implementation of "Sleep Timer" to music player;
![PicsArt_06-14-11.31.35.png](https://cdn.steemitimages.com/DQmbTDcCGKqjHMBkgTqcLaCRPmjZiJoEt64MiUTvrPg97Dd/PicsArt_06-14-11.31.35.png)
* This is how i suggest to add “Sort" feature to app:
![PicsArt_06-14-11.31.29.png](https://cdn.steemitimages.com/DQmRbHvYJ7T4kJ46K6ULFt7geNqjMjNppvuscRoib8LuotA/PicsArt_06-14-11.31.29.png) 

#### Benefits:
Benefits of implementing these features in this ACG-Player are as under:
* By implementing “Online Music" to this app is that, user can listen any kind of music like Rock,Pop, Hip Hop, etc. Best feature of implementing this feature is it can save a lot of time and storage for user even user don't have to download any kind of music from external sources.
* By adding “Google Assistant" feature in app, user will be able to give commands in music player via voice like searching any song or playing any song.
* With the help of “Sleep Timer" feature, user can listen music for a particular time span, otherwise some user forgot to off music which results in battery drainage and some other problems.
* By implementing “Sort" feature in app, user can assemble songs according to his will where he wants to sort them in terms of size, name, alphabetical letters, etc. With the help of sort feature, user can find easily any song without wasting his time. In short it will help user to save time.

**Comment by AugustToko** [comment]
timer added

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
