### ISSUE TITLE
Search option is not working in "File Viewer" channel.

### ISSUE THREAD

**Issue by Xeeshuu** [Crypto-Android-Apps/ACG-Player#70]
After opening an app, i tried to search a folder from "File Viewer" channel, when i typed name of any folder then tried to click on "search" icon, it is not able to search that folder.
**Video/Screenshot**:
https://youtu.be/OobitGdsoEg
**System information:**
* Device: RedMi Y2/S2.
* OS: 8.1.0
* Version: 2.6.8.6(20190619){edited}

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
