### ISSUE TITLE
Error occurred when dark mode is kept on and then clicking on Exit.

### ISSUE THREAD

**Issue by Xeeshuu** [Crypto-Android-Apps/ACG-Player#76]
After opening an app, then enabled "Dark Mode". After enabling "Dark Mode" , i go back to music list and then clicked on 3 dots on top right corner. Then i clicked on **Exit** button. It shows loading....
**Screenshot/Video:**
https://youtu.be/kQQ96AsjkJk
**Device Information:**
* Android: RedMi Y2/S2.
* OS: 8.1.0
* App Version: 2.6.9.0(20190621)

**Comment by AugustToko** [comment]
try lastest version

**Comment by Xeeshuu** [comment]
I tried it.... But issue still occurs.

**Comment by Xeeshuu** [comment]
@AugustToko hey, have you fixed this issue??

**Comment by AugustToko** [comment]
may fixed, try lastest on release page

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
