### ISSUE TITLE
App crashes when I tried to play a song in an empty playlist section

### ISSUE THREAD

**Issue by iamowomizz** [Crypto-Android-Apps/ACG-Player#77]
**Describe the bug**
The app crashes when I tried to play a song in an empty playlist section 

**To Reproduce**
1. Launch the app 
2. Scroll to the play list section
3. Scroll down to an empty playlist and open it 
4. Click on the two arrow crossing each other 
5. App crashes

**Expected behavior**
I expect the app not to crash when I click on the two crossing arrows 

**Smartphone (please complete the following information):**
 - Device: [Infinix s2pro]
 - OS: [Android 7.0]
 - Version [2.6.9.1]

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
