### ISSUE TITLE
Can't play a song through the file viewer section using the Acg player.

### ISSUE THREAD

**Issue by iamowomizz** [Crypto-Android-Apps/ACG-Player#78]
**Describe the bug**
When I try to play a song in the file viewer section, using the acg player nothing happens.

**To Reproduce**
1. Launch the app 
2. Scroll to the File viewer section
3. Try to locate a folder with songs in it
4. Click on the song you've located and try to play the song using the acg player
5. The song doesn't get played 

**Expected behavior**
When I click on a song through the file viewer and play it using the acg player I expect the song to play.

**Smartphone (please complete the following information):**
 - Device: [Infinix s2pro]
 - OS: [Android 7.0]
 - Version [2.6.9.1]

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
