### ISSUE TITLE
Bug: The exit button freezes the app. 

### ISSUE THREAD

**Issue by darewealth** [Crypto-Android-Apps/ACG-Player#86]
**Describe the bug**
When I click the exit button to exit the app, it will keep loading until I had to use my mobile minimize button.

**To Reproduce**
1. Launch the app
2. Click on menu
3. Click on exit 

**Expected behavior**
I expect that the exit button will work to exit the app without any issues.

**Screenshots**
https://youtu.be/auKEThma6Xo

**Smartphone**
 - Device: [Gionee]
 - OS: [8.1]
 - Version [2.6.9.4]

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
