### ISSUE TITLE
[ACG-Player][v2.6.9.5]The application crashes when i click on Exit option

### ISSUE THREAD

**Issue by 44asad** [Crypto-Android-Apps/ACG-Player#88]
### Expected behavior:
I expected that the application should not be crash when i click on Exit option.

### Actual behavior:
After configure the application when i click on Exit option,the application is you can see in bug vieo proprealy.

### How to reproduce:
1.Download the app from playstore and open the app.
2.Then click on account manu icon
3.click on Exit option
6.Note the Bug.

### information
* App version:v2.6.9.5
* os:Android 6.0.1
* Device:samsung J5
### Recording of the bug
https://youtu.be/oo6w2jxc98o
### Logcat:
<pre><code>06-30 05:30:21.382 25803 25803 E AndroidRuntime: FATAL EXCEPTION: main
06-30 05:30:21.382 25803 25803 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 25803
06-30 05:30:21.382 25803 25803 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Ltop/geek_studio/chenlongcould/musicplayer/MyTileService;
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.activity.main.MainActivity.fullExit(SourceFile:3)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at top.geek_studio.chenlongcould.musicplayer.activity.main.MainActivity.onOptionsItemSelected(SourceFile:14)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.app.Activity.onMenuItemSelected(Activity.java:3205)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at b.o.a.k.onMenuItemSelected(SourceFile:1)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at b.c.a.n.onMenuItemSelected(SourceFile:1)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at b.c.f.j.onMenuItemSelected(SourceFile:1)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at b.c.f.j.onMenuItemSelected(SourceFile:1)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at b.c.a.D.onMenuItemClick(SourceFile:1)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(SourceFile:2)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(SourceFile:2)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at b.c.f.a.k.a(SourceFile:32)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at b.c.f.a.k.a(SourceFile:67)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at b.c.f.a.q.onItemClick(SourceFile:6)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.widget.AdapterView.performItemClick(AdapterView.java:346)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.widget.AbsListView.performItemClick(AbsListView.java:1547)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.widget.AbsListView$PerformClick.run(AbsListView.java:3826)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.widget.AbsListView$3.run(AbsListView.java:5848)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-30 05:30:21.382 25803 25803 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "top.geek_studio.chenlongcould.musicplayer.MyTileService" on path: DexPathList[[zip file "/data/app/top.geek_studio.chenlongcould.musicplayer.Common-1/base.apk"],nativeLibraryDirectories=[/data/app/top.geek_studio.chenlongcould.musicplayer.Common-1/lib/arm, /data/app/top.geek_studio.chenlongcould.musicplayer.Common-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   ... 24 more
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   Suppressed: java.lang.NoClassDefFoundError: top.geek_studio.chenlongcould.musicplayer.MyTileService06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at dalvik.system.DexFile.defineClassNative(Native Method)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at dalvik.system.DexFile.defineClass(DexFile.java:226)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at dalvik.system.DexPathList.findClass(DexPathList.java:338)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     ... 26 more
06-30 05:30:21.382 25803 25803 E AndroidRuntime:   Suppressed: java.lang.ClassNotFoundException: top.geek_studio.chenlongcould.musicplayer.MyTileService
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at java.lang.Class.classForName(Native Method)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-30 05:30:21.382 25803 25803 E AndroidRuntime:     ... 25 more</code></pre>

**Comment by 44asad** [comment]
@AugustToko feadback please

**Comment by AugustToko** [comment]
> @AugustToko feadback please

try new version (release page)

**Comment by 44asad** [comment]
@ AugustToko released this yesterday update this version.so!

**Comment by AugustToko** [comment]
> @ AugustToko released this yesterday update this version.so!

i updated just now

**Comment by 44asad** [comment]
ok

**Comment by 44asad** [comment]
@AugustToko version v2.6.9.5 and new version v2.6.9.6 same problem.so feadback please.

**Comment by AugustToko** [comment]
> @AugustToko version v2.6.9.5 and new version v2.6.9.6 same problem.so feadback please.

same log？

**Comment by 44asad** [comment]
yea brother!

**Comment by AugustToko** [comment]
Upgrade to ACG Player X
Uninstall old version
[ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
