### ISSUE TITLE
Whole system of mobile phone gets into Dark Mode when ACG-Player is being used in Dark Mode.

### ISSUE THREAD

**Issue by Xeeshuu** [Crypto-Android-Apps/ACG-Player#89]
When I opened an app, i set it into Dark Mode and then Exited the app. After going to my home screen, whole system of my phone gets into Dark Mode.
**Screenshot/Video:**
https://youtu.be/JxKMwhkXvMA
**Device:**
* Android: RedMi Y2/S2.
* OS: 8.1.0
* App version: 2.6.9.6

**Comment by AugustToko** [comment]
Upgrade to ACG Player X
Uninstall old version
[ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases/tag/1.4.4(161))
