### ISSUE TITLE
Bug: unable to pay song after pausing on the drop bar notification.

### ISSUE THREAD

**Issue by darewealth** [Crypto-Android-Apps/ACG-Player#90]
**Describe the bug**
I played music on the app and I minimized the app, then I swiped down my notification bar to pause the song. After the music was paused I could not play the song again. 

**To Reproduce**

1. Launch the app 
2. Play any music 
3. Minimize the app 
4. Pause and play 
5. See error

**Expected behavior**
I expect the music to play back when I clicked the play function.

**Screenshots**
https://youtu.be/5lKaoDSaVVc

**Smartphone (please complete the following information):**
 - Device: [Gionee X1]
 - OS: [7.0]
 - Version[2.6.9.6]

**Comment by AugustToko** [comment]
Upgrade to ACG Player X
Uninstall old version
[ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases/tag/1.4.4(161))
